version: '3.1'

services:
  insightify:
    container_name: insightify
    env_file: ./insightify-frontend/.env.production
    build: ./insightify-frontend
    ports:
      - 3000:3000
    depends_on:
      - insightify_cdn
  insightify_cdn:
    container_name: insightify_cdn
    env_file: ./insightify_cdn/.env.production
    build: ./insightify_cdn
    ports:
      - 3001:3001
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  nginx:
        build: ./nginx
        ports:
            - '80:80'
        depends_on:
            - insightify

volumes:
  mongo_data:
